from __future__ import annotations

import re
from collections import OrderedDict

from toolchain.compiler.loader import ModuleGraph
from toolchain.compiler.semantic_ir import build_semantic_ir

TS_PRIMITIVES = {
    "Int": "number",
    "Float": "number",
    "Decimal": "number",
    "Bool": "boolean",
    "String": "string",
    "Bytes": "string",
    "Instant": "string",
    "Duration": "string",
    "Uuid": "string",
    "Email": "string",
    "UserId": "string",
    "TenantId": "string",
    "Principal": "Record<string, unknown>",
}


def _split_qualified(name: str) -> tuple[str | None, str]:
    if "." in name:
        left, right = name.rsplit(".", 1)
        return left, right
    return None, name


def _ts_type(type_name: str, current_module: str) -> str:
    qualifier, bare = _split_qualified(type_name)
    if qualifier is None and bare in TS_PRIMITIVES:
        return TS_PRIMITIVES[bare]
    module_name = qualifier or current_module
    return f"{module_name}_{bare}"


def _extract_path_params(path: str) -> list[str]:
    return re.findall(r"\{([^{}]+)\}", path)


def emit_ts_client(module_graph: ModuleGraph) -> str:
    ir = build_semantic_ir(module_graph)
    lines: list[str] = []
    lines.append("// Generated by Astra TypeScript client emitter")
    lines.append("/* eslint-disable */")
    lines.append("")
    lines.append("export interface AstraClientOptions {")
    lines.append("  baseUrl?: string;")
    lines.append("  fetchImpl?: typeof fetch;")
    lines.append("  headers?: HeadersInit;")
    lines.append("}")
    lines.append("")
    lines.append("export class AstraClient {")
    lines.append("  readonly baseUrl: string;")
    lines.append("  readonly fetchImpl: typeof fetch;")
    lines.append("  readonly headers: HeadersInit;")
    lines.append("")
    lines.append("  constructor(options: AstraClientOptions = {}) {")
    lines.append("    this.baseUrl = options.baseUrl ?? \"\";")
    lines.append("    this.fetchImpl = options.fetchImpl ?? fetch;")
    lines.append("    this.headers = options.headers ?? {}; ")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    for module_name, module_ir in ir.modules.items():
        for schema in module_ir.schemas:
            iface_name = f"{module_name}_{schema.name}"
            lines.append(f"export interface {iface_name} {{")
            for field in schema.fields:
                lines.append(f"  {field.name}: {_ts_type(field.type_ref.qualified_name, module_name)};")
            lines.append("}")
            lines.append("")
        for command in module_ir.commands:
            iface_name = f"{module_name}_{command.name}"
            lines.append(f"export interface {iface_name} {{")
            for field in command.fields:
                lines.append(f"  {field.name}: {_ts_type(field.type_ref.qualified_name, module_name)};")
            lines.append("}")
            lines.append("")
        for event in module_ir.events:
            iface_name = f"{module_name}_{event.name}"
            lines.append(f"export interface {iface_name} {{")
            for field in event.fields:
                lines.append(f"  {field.name}: {_ts_type(field.type_ref.qualified_name, module_name)};")
            lines.append("}")
            lines.append("")

    route_counter = 0
    for module_name, module_ir in ir.modules.items():
        command_map = {c.name: c for c in module_ir.commands}
        query_map = {q.name: q for q in module_ir.queries}
        for api in module_ir.apis:
            for route in api.routes:
                route_counter += 1
                target_module, target_name = _split_qualified(route.target)
                target_module = target_module or module_name
                params = _extract_path_params(route.path)
                method_name = f"{module_name}_{api.name}_{route.method}_{target_name}".replace("-", "_")
                arg_list: list[str] = ["client: AstraClient"]
                for p in params:
                    query = query_map.get(target_name) if target_module == module_name else None
                    param_type = "string"
                    if query and query.input_type and p.lower() in {"id", "userid", "tenantid"}:
                        param_type = _ts_type(query.input_type.qualified_name, target_module)
                    arg_list.append(f"{p}: {param_type}")
                if route.target_kind == "command":
                    arg_list.append(f"payload: {target_module}_{target_name}")
                    return_type = "Promise<Response>"
                else:
                    query = query_map.get(target_name) if target_module == module_name else None
                    return_type = f"Promise<{_ts_type(query.output_type.qualified_name, target_module)}>" if query and query.output_type else "Promise<unknown>"
                lines.append(f"export async function {method_name}({', '.join(arg_list)}): {return_type} {{")
                path_expr = route.path
                for p in params:
                    path_expr = path_expr.replace("{" + p + "}", "${encodeURIComponent(String(" + p + "))}")
                lines.append(f"  const url = `${{client.baseUrl}}{path_expr}`;")
                if route.target_kind == "command":
                    lines.append("  return client.fetchImpl(url, {")
                    lines.append(f"    method: \"{route.method.upper()}\",")
                    lines.append("    headers: { \"content-type\": \"application/json\", ...client.headers },")
                    lines.append("    body: JSON.stringify(payload),")
                    lines.append("  });")
                else:
                    lines.append("  const response = await client.fetchImpl(url, {")
                    lines.append(f"    method: \"{route.method.upper()}\",")
                    lines.append("    headers: { ...client.headers },")
                    lines.append("  });")
                    lines.append("  return await response.json();")
                lines.append("}")
                lines.append("")

    if route_counter == 0:
        lines.append("// No API routes were found in the workspace.")
    return "\n".join(lines).rstrip() + "\n"
