from __future__ import annotations

from toolchain.compiler.loader import ModuleGraph
from toolchain.emitters.jsonschema import _split_qualified

TS_PRIMITIVE_MAP = {
    "Int": "number",
    "Float": "number",
    "Decimal": "number",
    "Bool": "boolean",
    "String": "string",
    "Bytes": "string",
    "Instant": "string",
    "Duration": "string",
    "Uuid": "string",
    "Email": "string",
    "UserId": "string",
    "TenantId": "string",
    "Principal": "Record<string, unknown>",
}

HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def _ts_type(current_module: str, type_name: str) -> str:
    qualifier, bare = _split_qualified(type_name)
    if qualifier is None and bare in TS_PRIMITIVE_MAP:
        return TS_PRIMITIVE_MAP[bare]
    if bare in TS_PRIMITIVE_MAP:
        return TS_PRIMITIVE_MAP[bare]
    return bare


def _find_query(module_graph: ModuleGraph, current_module: str, target: str):
    qualifier, bare = _split_qualified(target)
    module_name = qualifier or current_module
    loaded = module_graph.modules.get(module_name)
    if not loaded:
        return None
    return next((q for q in loaded.module.queries if q.name == bare), None)



def _route_function_name(path: str, method: str, target: str) -> str:
    _, bare = _split_qualified(target)
    if bare:
        return bare[0].lower() + bare[1:]
    compact = path.strip("/").replace("/", "_").replace("{", "").replace("}", "") or "root"
    return f"{method.lower()}_{compact}"



def emit_ts_client(module_graph: ModuleGraph) -> str:
    lines: list[str] = []
    lines.append("/* Auto-generated by Astra TypeScript client emitter. */")
    lines.append("")

    exported_models: list[tuple[str, object, str]] = []
    for module_name, loaded in module_graph.modules.items():
        for decl in [*loaded.module.schemas, *loaded.module.commands, *loaded.module.events]:
            exported_models.append((module_name, decl, "interface"))
        for decl in loaded.module.type_aliases:
            exported_models.append((module_name, decl, "alias"))

    for module_name, decl, kind in exported_models:
        if kind == "alias":
            lines.append(f"export type {decl.name} = {_ts_type(module_name, decl.target_type)};")
            lines.append("")
            continue
        lines.append(f"export interface {decl.name} {{")
        for field in decl.fields:
            lines.append(f"  {field.name}: {_ts_type(module_name, field.type_name)};")
        lines.append("}")
        lines.append("")

    lines.append("export interface AstraClientOptions {")
    lines.append("  baseUrl: string;")
    lines.append("  fetchImpl?: typeof fetch;")
    lines.append("  defaultHeaders?: HeadersInit;")
    lines.append("}")
    lines.append("")
    lines.append("export class AstraClient {")
    lines.append("  private readonly baseUrl: string;")
    lines.append("  private readonly fetchImpl: typeof fetch;")
    lines.append("  private readonly defaultHeaders?: HeadersInit;")
    lines.append("")
    lines.append("  constructor(options: AstraClientOptions) {")
    lines.append("    this.baseUrl = options.baseUrl.replace(/\\/$/, '');")
    lines.append("    this.fetchImpl = options.fetchImpl ?? fetch;")
    lines.append("    this.defaultHeaders = options.defaultHeaders;")
    lines.append("  }")
    lines.append("")

    for module_name, loaded in module_graph.modules.items():
        for api in loaded.module.apis:
            for route in api.routes:
                method = route.method.lower()
                if method not in HTTP_METHODS:
                    continue
                fn_name = _route_function_name(route.path, method, route.target)
                qualifier, bare = _split_qualified(route.target)
                target_module = qualifier or module_name
                query = _find_query(module_graph, module_name, route.target)
                is_command = any(c.name == bare for c in module_graph.modules[target_module].module.commands)
                path_params = []
                for segment in route.path.split("{"):
                    if "}" in segment:
                        param = segment.split("}", 1)[0]
                        path_params.append(param)
                params: list[str] = []
                arg_lines: list[str] = []
                for param in path_params:
                    params.append(f"{param}: string")
                if is_command:
                    params.append(f"body: {bare}")
                if query and query.output_type:
                    return_type = _ts_type(target_module, query.output_type)
                else:
                    return_type = "void"
                lines.append(f"  async {fn_name}({', '.join(params)}) : Promise<{return_type}> {{")
                url_expr = route.path.replace('{', '${')
                lines.append(f"    const url = `${{this.baseUrl}}{url_expr}`;")
                lines.append("    const response = await this.fetchImpl(url, {")
                lines.append(f"      method: '{method.upper()}',")
                if is_command:
                    lines.append("      headers: { 'Content-Type': 'application/json', ...(this.defaultHeaders ?? {}) },")
                    lines.append("      body: JSON.stringify(body),")
                else:
                    lines.append("      headers: this.defaultHeaders,")
                lines.append("    });")
                lines.append("    if (!response.ok) {")
                lines.append("      throw new Error(`Astra request failed: ${response.status} ${response.statusText}`);")
                lines.append("    }")
                if return_type != "void":
                    lines.append(f"    return (await response.json()) as {return_type};")
                lines.append("  }")
                lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)
